version: "3.9"

services:
  lite:
    container_name: "lite_server"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    ports:
        - "5000:3000"
    restart: "no"
    command: "lite-server"