version: "3.9"

services:
  json:
    container_name: "json_server"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    ports:
      - "7000:3000"
    restart: "no"
    volumes: 
      - "./data:/data"
    command: "--watch db.json"