version: "3.9"

services:
  lite_serv:
    build:
      context: "./"
      dockerfile: "./lite/Dockerfile"
    restart: "no"
    command: "lite-server"
  json_serv:
    build:
      context: "./"
      dockerfile: "./json/Dockerfile"
    restart: "no"
    volumes: 
      - "./data:/data"
    command: "--watch /db.json"
  nginx_web:
    image: nginx
    volumes: 
      - "./conf:/etc/nginx"
    ports:
      - "2000:80"
      - "1000:81"
    links: 
      - json_serv
      - lite_serv